from sqlalchemy import Column, String, Integer, ForeignKey, Text, CHAR, DECIMAL, VARCHAR
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.dialects.postgresql import UUID
import uuid

'''
    In the shoppingCart services, we need the following tables:
    - ShoppingCart: This table will store the shopping cart information. It will have a one-to-many relationship with the ShoppingCartItem table.
    - ShoppingCartItem: This table will store the items in the shopping cart. It will have a many-to-one relationship with the ShoppingCart table.
    - Customer: This table will store the customer information. It will have a one-to-many relationship with the ShoppingCart table.
    - product: This table will store the product information. It will have a one-to-many relationship with the ShoppingCartItem table.    

    not:
        in the user related tables, id is auto increment, but in the shopping cart related tables, id is generated by uuid .
'''

Base = declarative_base()

# uuid will help us to generate unique ids for the shopping cart and shopping cart  
class ShoppingCart(Base):
    __tablename__ = 'shoppingcart' # name of the table in the database
    cart_id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4())) # primary key
    customer_id = Column(String(36), ForeignKey('customers.user_id'), nullable=True) # foreign key
    cart_status = Column(String(50), nullable=False) # status of the cart (active, inactive, ordered)

    # when we define relationship in orm, we give name of the class, not the table name and the back_populates parameter is used to define the relationship in the other class
    items = relationship("ShoppingCartItem", back_populates="cart") # one-to-many relationship

class ShoppingCartItem(Base):
    __tablename__ = 'shoppingcart_item'
    shopping_cart_item_id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    cart_id = Column(String(36), ForeignKey('shoppingcart.cart_id'))
    product_id = Column(String(36), ForeignKey('products.product_id'))
    quantity = Column(Integer, nullable=False, default=1)

    cart = relationship("ShoppingCart", back_populates="items") # many-to-one relationship

# User types
class Customer(Base):
    __tablename__ = "customers"

    # This line is crucial for the database to work properly.
    # Eğer auto increment olmazsa: user_id user dan alınmadığından dolayı hata alırız. 
    user_id = Column(Integer, primary_key=True, autoincrement=True)  
    name = Column(String)
    middlename = Column(String, nullable=True)
    surname = Column(String)
    email = Column(String, unique=True)
    password = Column(String)
    phone_number = Column(String, nullable=True)

class Admin(Base):
    __tablename__ = 'admins'
    admin_id = Column(CHAR(36), primary_key=True, autoincrement=True)
    name = Column(String(50), nullable=False)
    middlename = Column(String(50))
    surname = Column(String(50), nullable=False)
    email = Column(String(100), nullable=False, unique=True)
    password = Column(String(255), nullable=False)
    phone_number = Column(String(20))

class ProductManager(Base):
    __tablename__ = 'product_managers'
    pm_id = Column(CHAR(36), primary_key=True, autoincrement=True)
    name = Column(String(50), nullable=False)
    middlename = Column(String(50))
    surname = Column(String(50), nullable=False)
    email = Column(String(100), nullable=False, unique=True)
    password = Column(String(255), nullable=False)
    phone_number = Column(String(20))

class SalesManager(Base):
    __tablename__ = 'sales_managers'
    sm_id = Column(CHAR(36), primary_key=True, autoincrement=True)
    name = Column(String(50), nullable=False)
    middlename = Column(String(50))
    surname = Column(String(50), nullable=False)
    email = Column(String(100), nullable=False, unique=True)
    password = Column(String(255), nullable=False)
    phone_number = Column(String(20))


class Product(Base):
    __tablename__ = 'products'

    # columns of the table
    product_id = Column(CHAR(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    name = Column(VARCHAR(100), nullable=False)
    model = Column(VARCHAR(50), nullable=False)
    description = Column(Text, nullable=True)
    category_id = Column(Integer, ForeignKey('category.category_id', ondelete='SET NULL'), nullable=True)
    serial_number = Column(VARCHAR(100), unique=True, nullable=False)
    quantity = Column(Integer, nullable=False, default=0)
    warranty_status = Column(Integer, nullable=True)
    distributor = Column(VARCHAR(100), nullable=True)
    image_url = Column(VARCHAR(255), nullable=True)
    price = Column(DECIMAL(10, 2), nullable=False, default=0.00)
    item_sold = Column(Integer, nullable=False, default=0)

    def __repr__(self):
        return f"<Product(name={self.name}, model={self.model}, quantity={self.quantity})>"


from pydantic import BaseModel

# pdyanctic model for the cart item which is to be used when adding an item to the cart with certain quantity
class CartItem(BaseModel):
    product_id: str
    quantity: int

# Pydantic model for product quantity adjustments coming from the frontend (for proper type hinting)
class CartAdjustment(BaseModel):
    product_id: str
    customer_id: str
